<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="inertial_macros.xacro"/>
    
    <xacro:property name="chassis_length" value="0.20" /> 
    <xacro:property name="chassis_width" value="0.20" /> 
    <xacro:property name="chassis_height" value="0.13" /> 
    <xacro:property name="chassis_mass" value="1.0" /> 
    <xacro:property name="wheel_radius" value="0.032" /> 
    <xacro:property name="wheel_thickness" value="0.026" /> 
    <xacro:property name="wheel_mass" value="0.5" /> 
    <xacro:property name="wheel_offset_x" value="0.226" /> 
    <xacro:property name="wheel_offset_y" value="0.113" /> 
    <xacro:property name="wheel_offset_z" value="${wheel_radius}" /> 
    <xacro:property name="caster_wheel_radius" value="0.03" /> 
    <xacro:property name="caster_wheel_mass" value="0.01" /> 
    <xacro:property name="caster_wheel_offset_x" value="0.06" /> 
    <xacro:property name="caster_wheel_offset_z" value="-${chassis_height/2}" /> 



    <!-- MATERIALS -->
    <material name="white">
        <color rgba="1 1 1 1 " />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1 " />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1 " />
    </material>

    <material name="black">
        <color rgba="0 0 0 1 " />-
    </material>

    <material name="red">
        <color rgba="1 0 0 1 " />
    </material>


    <!-- BASE LINK-->

    <link name="base_link">0

    </link>

    <!-- CHASSIS-->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0.04 0 ${chassis_height/2 + wheel_radius}" />
    </joint>
z
    <link name="chassis">
        <visual>
            <geometry>
                <box size="0.20 0.20 0.13"/>
            </geometry>  
            <material name="black"/>  
        </visual>
        <collision>
            <origin xyz="0 0 0" />
            <geometry>
                <box size="0.20 0.20 0.13"/>
            </geometry>   
        </collision>
        <xacro:inertial_box mass="0.5" x="0" y="0.3" z="0.15">
            <origin xyz="0.15 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- LEFT WHEEL LINK-->

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel"/>  
        <axis xyz="0 0 1"/>
          
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>    
            </geometry>
            <material name="blue"/>    
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>    
            </geometry>  
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>    
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK-->

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 -${wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel"/>  
        <axis xyz="0 0 -1"/>
          
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>    
            </geometry>
            <material name="blue"/>    
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>    
            </geometry>  
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>    
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL-->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>    
            </geometry> 
            <material name="blue"/>     
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>    
            </geometry>  
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/> 
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.0001"/>
        <mu2 value="0.0001"/>
    </gazebo>

</robot>